# Generated by Django 3.1.7 on 2021-04-22 21:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UnemployedUpliftingContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Article Name')),
                ('description', models.CharField(max_length=200, verbose_name='Article Description')),
                ('img_url', models.URLField(max_length=500, verbose_name='Image URL')),
                ('src', models.CharField(max_length=200, verbose_name='Article Source')),
                ('article_link', models.URLField(max_length=500, verbose_name='Article URL')),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='unemployed_uplifting_content', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Unemployed User's Uplifting Content",
                'verbose_name_plural': 'Unemployed User Uplifting Content',
            },
        ),
        migrations.CreateModel(
            name='UnemployedMeditation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Meditation Name')),
                ('description', models.TextField(max_length=200, verbose_name='Meditation Description')),
                ('benefit', models.CharField(choices=[('happiness', 'Happiness'), ('acceptance', 'Acceptance'), ('resilience', 'Resilience'), ('relaxation', 'Relaxation'), ('letting go', 'Letting Go'), ('depression', 'Depression'), ('anxiety', 'Anxiety'), ('stress', 'Stress'), ('grief', 'Grief'), ('healing', 'Healing'), ('workplace', 'Workplace'), ('sleep', 'Sleep'), ('gratitude', 'Gratitude'), ('body scan', 'Body Scan')], max_length=200, verbose_name='Benefit')),
                ('length', models.DurationField(verbose_name='Meditation Length')),
                ('audio', models.FileField(upload_to='', verbose_name='Meditation Audio File')),
                ('meditation_link', models.URLField(max_length=500, verbose_name='Meditation URL')),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='unemployed_meditation', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Unemployed User's Meditation",
                'verbose_name_plural': 'Unemployed User Meditations',
            },
        ),
        migrations.CreateModel(
            name='MentalHealthUpliftingContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Article Name')),
                ('description', models.CharField(max_length=200, verbose_name='Article Description')),
                ('img_url', models.URLField(max_length=500, verbose_name='Image URL')),
                ('src', models.CharField(max_length=200, verbose_name='Article Source')),
                ('article_link', models.URLField(max_length=500, verbose_name='Article URL')),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='mentalhealth_uplifting_content', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Mental Health's Uplifting Content",
                'verbose_name_plural': 'Mental Health Uplifting Content',
            },
        ),
        migrations.CreateModel(
            name='MentalHealthMeditation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Meditation Name')),
                ('description', models.TextField(max_length=200, verbose_name='Meditation Description')),
                ('benefit', models.CharField(choices=[('happiness', 'Happiness'), ('acceptance', 'Acceptance'), ('resilience', 'Resilience'), ('relaxation', 'Relaxation'), ('letting go', 'Letting Go'), ('depression', 'Depression'), ('anxiety', 'Anxiety'), ('stress', 'Stress'), ('grief', 'Grief'), ('healing', 'Healing'), ('sleep', 'Sleep'), ('gratitude', 'Gratitude'), ('body scan', 'Body Scan')], max_length=200, verbose_name='Benefit')),
                ('length', models.DurationField(verbose_name='Meditation Length')),
                ('audio', models.FileField(upload_to='', verbose_name='Meditation Audio File')),
                ('meditation_link', models.URLField(max_length=500, verbose_name='Meditation URL')),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='mentalhealth_meditation', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Mental Health User's Meditation",
                'verbose_name_plural': 'Mental Health User Meditations',
            },
        ),
        migrations.CreateModel(
            name='LossUpliftingContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Article Name')),
                ('description', models.CharField(max_length=200, verbose_name='Article Description')),
                ('img_url', models.URLField(max_length=500, verbose_name='Image URL')),
                ('src', models.CharField(max_length=200, verbose_name='Article Source')),
                ('article_link', models.URLField(max_length=500, verbose_name='Article URL')),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='loss_uplifting_content', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Loss User's Uplifting Content",
                'verbose_name_plural': 'Loss User Uplifting Content',
            },
        ),
        migrations.CreateModel(
            name='LossMeditation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Meditation Name')),
                ('description', models.TextField(max_length=200, verbose_name='Meditation Description')),
                ('benefit', models.CharField(choices=[('happiness', 'Happiness'), ('acceptance', 'Acceptance'), ('resilience', 'Resilience'), ('relaxation', 'Relaxation'), ('letting go', 'Letting Go'), ('depression', 'Depression'), ('anxiety', 'Anxiety'), ('stress', 'Stress'), ('grief', 'Grief'), ('healing', 'Healing'), ('sleep', 'Sleep'), ('gratitude', 'Gratitude'), ('body scan', 'Body Scan')], max_length=200, verbose_name='Benefit')),
                ('length', models.DurationField(verbose_name='Meditation Length')),
                ('audio', models.FileField(upload_to='', verbose_name='Meditation Audio File')),
                ('meditation_link', models.URLField(max_length=500, verbose_name='Meditation URL')),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='loss_meditation', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Loss User's Meditation",
                'verbose_name_plural': 'Loss User Meditations',
            },
        ),
        migrations.CreateModel(
            name='IsolatedUpliftingContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Article Name')),
                ('description', models.CharField(max_length=200, verbose_name='Article Description')),
                ('img_url', models.URLField(max_length=500, verbose_name='Image URL')),
                ('src', models.CharField(max_length=200, verbose_name='Article Source')),
                ('article_link', models.URLField(max_length=500, verbose_name='Article URL')),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='isolated_uplifting_content', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Isolated User's Uplifting Content",
                'verbose_name_plural': 'Isolated User Uplifting Content',
            },
        ),
        migrations.CreateModel(
            name='IsolatedMeditation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Meditation Name')),
                ('description', models.TextField(max_length=200, verbose_name='Meditation Description')),
                ('benefit', models.CharField(choices=[('happiness', 'Happiness'), ('acceptance', 'Acceptance'), ('resilience', 'Resilience'), ('relaxation', 'Relaxation'), ('letting go', 'Letting Go'), ('depression', 'Depression'), ('anxiety', 'Anxiety'), ('stress', 'Stress'), ('grief', 'Grief'), ('healing', 'Healing'), ('sleep', 'Sleep'), ('gratitude', 'Gratitude'), ('body scan', 'Body Scan')], max_length=200, verbose_name='Benefit')),
                ('length', models.DurationField(verbose_name='Meditation Length')),
                ('audio', models.FileField(upload_to='', verbose_name='Meditation Audio File')),
                ('meditation_link', models.URLField(max_length=500, verbose_name='Meditation URL')),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='isolated_meditation', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Isolated User's Meditation",
                'verbose_name_plural': 'Isolated User Meditations',
            },
        ),
        migrations.CreateModel(
            name='FrontlineUpliftingContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Article Name')),
                ('description', models.CharField(max_length=200, verbose_name='Article Description')),
                ('img_url', models.URLField(max_length=500, verbose_name='Image URL')),
                ('src', models.CharField(max_length=200, verbose_name='Article Source')),
                ('article_link', models.URLField(max_length=500, verbose_name='Article URL')),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='frontline_uplifting_content', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Frontline User's Uplifting Content",
                'verbose_name_plural': 'Frontline User Uplifting Content',
            },
        ),
        migrations.CreateModel(
            name='FrontlineMeditation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Meditation Name')),
                ('description', models.TextField(max_length=200, verbose_name='Meditation Description')),
                ('benefit', models.CharField(choices=[('happiness', 'Happiness'), ('acceptance', 'Acceptance'), ('resilience', 'Resilience'), ('relaxation', 'Relaxation'), ('letting go', 'Letting Go'), ('depression', 'Depression'), ('anxiety', 'Anxiety'), ('stress', 'Stress'), ('grief', 'Grief'), ('healing', 'Healing'), ('workplace', 'Workplace'), ('sleep', 'Sleep'), ('gratitude', 'Gratitude'), ('body scan', 'Body Scan')], max_length=200, verbose_name='Benefit')),
                ('length', models.DurationField(verbose_name='Meditation Length')),
                ('audio', models.FileField(upload_to='', verbose_name='Meditation Audio File')),
                ('meditation_link', models.URLField(max_length=500, verbose_name='Meditation URL')),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='frontline_meditation', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Frontline User's Meditation",
                'verbose_name_plural': 'Frontline User Meditations',
            },
        ),
    ]
