# Generated by Django 3.1.7 on 2021-04-29 13:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Journal Title')),
                ('body', models.TextField(max_length=3000, verbose_name='Journal Body')),
                ('date_created', models.DateField(auto_now_add=True, verbose_name='Journal Date Created')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_journals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Journal Entry',
                'verbose_name_plural': 'User Journal Entries',
            },
        ),
    ]
