# Generated by Django 3.1.7 on 2021-04-23 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallflower', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='frontlinemeditation',
            name='benefit',
        ),
        migrations.RemoveField(
            model_name='isolatedmeditation',
            name='benefit',
        ),
        migrations.RemoveField(
            model_name='lossmeditation',
            name='benefit',
        ),
        migrations.RemoveField(
            model_name='mentalhealthmeditation',
            name='benefit',
        ),
        migrations.RemoveField(
            model_name='unemployedmeditation',
            name='benefit',
        ),
    ]
