# Generated by Django 3.1.7 on 2021-04-26 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallflower', '0002_auto_20210423_1637'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='frontlinemeditation',
            name='user',
        ),
        migrations.RemoveField(
            model_name='frontlineupliftingcontent',
            name='user',
        ),
        migrations.RemoveField(
            model_name='isolatedmeditation',
            name='user',
        ),
        migrations.RemoveField(
            model_name='isolatedupliftingcontent',
            name='user',
        ),
        migrations.RemoveField(
            model_name='lossmeditation',
            name='user',
        ),
        migrations.RemoveField(
            model_name='lossupliftingcontent',
            name='user',
        ),
        migrations.RemoveField(
            model_name='mentalhealthmeditation',
            name='user',
        ),
        migrations.RemoveField(
            model_name='mentalhealthupliftingcontent',
            name='user',
        ),
        migrations.RemoveField(
            model_name='unemployedmeditation',
            name='user',
        ),
        migrations.RemoveField(
            model_name='unemployedupliftingcontent',
            name='user',
        ),
    ]
