# Generated by Django 3.1.7 on 2021-04-27 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallflower', '0004_auto_20210427_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frontlineupliftingnews',
            name='image',
            field=models.FileField(upload_to='', verbose_name='Article Image'),
        ),
        migrations.AlterField(
            model_name='isolatedupliftingnews',
            name='image',
            field=models.FileField(upload_to='', verbose_name='Article Image'),
        ),
        migrations.AlterField(
            model_name='lossupliftingnews',
            name='image',
            field=models.FileField(upload_to='', verbose_name='Article Image'),
        ),
        migrations.AlterField(
            model_name='mentalhealthupliftingnews',
            name='image',
            field=models.FileField(upload_to='', verbose_name='Article Image'),
        ),
        migrations.AlterField(
            model_name='unemployedupliftingnews',
            name='image',
            field=models.FileField(upload_to='', verbose_name='Article Image'),
        ),
    ]
