# Generated by Django 3.1.7 on 2021-04-27 19:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wallflower', '0005_auto_20210427_1608'),
    ]

    operations = [
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('journal_title', models.CharField(max_length=200, verbose_name='Journal Title')),
                ('journal_bodytext', models.TextField(max_length=3000, verbose_name='Journal Body')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_journals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Journal Entry',
                'verbose_name_plural': 'User Journal Entries',
            },
        ),
    ]
